#!/usr/bin/sh
#aclocal; autoconf; automake -a ;autoheader; ./configure FCFLAGS="-O4";make
aclocal; autoconf;automake -a;autoheader;./configure;make
#autoreconf -vi
#autoreconf;./configure; make
#automake -a; autoconf;./configure; make
#aclocal; automake -a; autoheader; autoconf; ./configure FCFLAGS="-O4"; make
