#/usr/bin/perl

for(my $i=10;$i<20;$i++){
    

#$depthkm=200.e0;

    $depthkm=10.e0*$i;


$psvmodel = "./ak135.psv.model";
$modelname = "ak135";
$backPropagationSwitch = 1;
$mpiSGTforPinv = "/users/p09101/chevrot/programs_fuji/SGTforPinv-0.1-MPI/mpiSGTforPinv";
#--------------------------------------------------
$depth=sprintf '%d',$depthkm;
$outputDir = "/tmpdir/chevrot/ak135/1600depth".$depth;
$logDir = $outputDir."/log";
$RSGTDir = $outputDir."/RSGT";
$TSGTDir = $outputDir."/TSGT";
$inputFile = "./input".$depth.".inf";
$qsubFile = "./qsub.".$depth;


system "mkdir $outputDir";
system "mkdir $logDir";
system "mkdir $RSGTDir";
system "mkdir $TSGTDir";

open FILE, ">$inputFile";
print FILE "\# This is the input file for SGTforPinv generated by makingInputFile.pl\n";
print File "\#\n";
print FILE "\#\n";
print FILE "\# 1. outputDir\n";
print FILE "$outputDir\n";
print FILE "\# 2. psvmodel\n";
print FILE "$psvmodel\n";
print FILE "\# 3. modelname\n";
print FILE "$modelname\n";
print FILE "\# 4. tlen (preferred to be set as 2\^n\*0.1 seconds\n";
print FILE "1.6384d3\n";
print FILE "\# 5. minQ radius (km), maxQ radius, delta radius\n";
print FILE "3481.d0 6371.d0 20.d0\n";
print FILE "\# 6. source radius (km)\n";
printf FILE '%e', 6371.e0-$depthkm;
print FILE "\n";
print FILE "\# 7. minQ theta (degrees), maxQ theta, delta theta\n";
print FILE "1.d-1 179.9d0 1.d-1\n";
print FILE "\# 8. imin imax (omega index: tlen/imax is the shortest period)\n";
print FILE "0 2048\n";
print FILE "\# 9. backpropagation (RSGT) calculation switch\n";
print FILE "\# if 1 we calculate\n";
print FILE "$backPropagationSwitch\n";
print FILE "\# don't forget to write \'end\'\n";
print FILE "end\n";
close FILE;


open FILE, ">$qsubFile";
print FILE "\#PBS -S /bin/bash\n";
print FILE "\#PBS -N d$depth\n";
print FILE "\#PBS -l select=16:ncpus=8:mpiprocs=8\n";
print FILE "\#PBS -l walltime=100:00:00\n";
print FILE "\#PBS -j oe\n";
print FILE "\n";
print FILE "cd \$PBS_O_WORKDIR \# on se place dans le repertoire courant\n";
print FILE ". \$MODULESHOME/init/sh\n";
print FILE "module load default-intel-mpi\n";
print FILE "cat \$PBS_NODEFILE | uniq \> mpd.hosts$depth\n";
print FILE "cat \$PBS_NODEFILE \> nodes$depth\n";
print FILE "mpdboot --rsh=ssh -v -n \`cat mpd.hosts$depth | wc -l\` -f mpd.hosts$depth\n";
print FILE "mpiexec -machinefile nodes$depth -np 128  $mpiSGTforPinv < $inputFile > output_test_$depth\n";
close FILE;




system "qsub $qsubFile";


}
