#!/usr/bin/perl

$DSMHOME = "/stockage/nfuji/DSM-KS2012beta.20120420/";
#$DSMHOME = "/stockage/nfuji/DSM-KS2011/";
$modelname = "ak135";
$outputDirDir = "/stockage/nfuji/".$modelname;
$npmpi = 16;
$emailaddress = "nobuaki\@ipgp.fr";

unless(-d $outputDirDir){
    system "mkdir $outputDirDir";
}


#--------------------------------------------------------------

$psvmodel= $DSMHOME."/etc/models/".$modelname.".psv.model";
$mpiSGTpsv = $DSMHOME."/bin/mpiSGTpsv";
$mpiSGTsh  = $DSMHOME."/bin/mpiSGTsh";

$switching = "1 1 1"; # for input.inf #9
$inf_calculDir = $DSMHOME."/inf_calcul/";
$DSMconfig = $DSMHOME."/etc/DSMconfiguration/DSM.config";

for(my $i=40;$i<=40;$i++){
    
    $depthkm=10.e0*$i;
    
#--------------------------------------------------------------
    
    $depth=sprintf '%d',$depthkm;
    
    $outputDir =$outputDirDir."/depth".$depth;
    $logDir = $outputDir."/log";
    $RSGTDir = $outputDir."/RSGT";
    $TSGTDir = $outputDir."/TSGT";
    $inputFile = $inf_calculDir."/input".$depth.".inf";
    $qsubFile =  $inf_calculDir."/qsub.".$depth;
    $execFile = $inf_calculDir."/exec".$depth.".sh";
    $logFile = $DSMHOME."/log/".$depth.".".$modelname.".psv.log";
    $logFileSH = $DSMHOME."/log/".$depth.".".$modelname.".sh.log";
    unless(-d $outputDir){
	system "mkdir $outputDir";
    }
    unless(-d $logDir){
	system "mkdir $logDir";
    }
    unless(-d $RSGTDir){
	system "mkdir $RSGTDir";
    }
    unless(-d $TSGTDir){
	system "mkdir $TSGTDir";
    }


    $outputDirLyon = "\/scratch\/nfuji\/depth$depth";
    
    open FILE, ">$inputFile";
    print FILE "\# This is the input file for SGTforPinv generated by makingInputFile.pl\n";
    print File "\#\n";
    print FILE "\# 0. DSM configuration file\n";
    print FILE "$DSMconfig \n";
    print FILE "\#\n";
    print FILE "\# 1. outputDir\n";
    print FILE "$outputDirLyon\n";
    print FILE "\# 2. psvmodel\n";
    print FILE "$psvmodel\n";
    print FILE "\# 3. modelname\n";
    print FILE "$modelname\n";
    print FILE "\# 4. tlen (preferred to be set as 2\^n\*0.1 seconds\n";
    print FILE "3.2768d3\n";
    print FILE "\# 5. minQ radius (km), maxQ radius, delta radius\n";
    print FILE "3651.d0 6371.d0 10.d0\n";
    print FILE "\# 6. source radius (km)\n";
    printf FILE '%e', 6371.e0-$depthkm;
    print FILE "\n";
    print FILE "\# 7. minQ theta (degrees), maxQ theta, delta theta\n";
    print FILE "0.d0 180.d0 2.d-1\n";
    print FILE "\# 8. imin imax (omega index: tlen/imax is the shortest period)\n";
    print FILE "0 256\n";
    print FILE "\# 9. switching calculation of RSGT, TSGT, synthetics\n";
    print FILE "\# if 1 we calculate\n";
    print FILE "$switching\n";
    print FILE "\# don't forget to write \'end\'\n";
    print FILE "end\n";
    close FILE;
    
    $numNode = $npmpi/16;
    open FILE, ">$qsubFile";
    print FILE "\#\!\/bin\/bash\n";	
    print FILE "\#PBS -N PSVd$depth\n";
    print FILE "\#PBS -l nodes=$numNode:ppn=16\n";
    print FILE "\#PBS -q P1d32c\n";
    print FILE "\#PBS -j oe\n";
    print FILE "\#PBS -M $emailaddress\n";
    print FILE "\#PBS -V\n";
    print FILE "cd \$\{PBS_O_WORKDIR\}\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/log\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/TSGT\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/RSGT\n";
    print FILE "mpirun -np $npmpi  $mpiSGTpsv < $inputFile > $logFile\n";
    #print FILE "mpirun -np $npmpi  $mpiSGTsh < $inputFile > $logFileSH\n"; 
    print FILE "mv \/scratch\/nfuji\/depth$depth\/TSGT\/\*PSV $TSGTDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/RSGT\/\*PSV $RSGTDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/log\/list.* $logDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/log\/calLog.* $logDir \n";
    print FILE "exit\n"; 
    close FILE;
   
    open FILE, ">$qsubFile\.SH";
    print FILE "\#\!\/bin\/bash\n";
    print FILE "\#PBS -N SHd$depth\n";
    print FILE "\#PBS -l nodes=$numNode:ppn=16\n";
    print FILE "\#PBS -q P1d32c\n";
    print FILE "\#PBS -j oe\n";
    print FILE "\#PBS -M $emailaddress\n";
    print FILE "\#PBS -V\n";
    print FILE "cd \$\{PBS_O_WORKDIR\}\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/log\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/TSGT\n";
    print FILE "mkdir \/scratch\/nfuji\/depth$depth\/RSGT\n";
    #print FILE "mpirun -np $npmpi  $mpiSGTpsv < $inputFile > $logFile\n";
    print FILE "mpirun -np $npmpi  $mpiSGTsh < $inputFile > $logFileSH\n"; 
    print FILE "mv \/scratch\/nfuji\/depth$depth\/TSGT\/\*SH $TSGTDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/RSGT\/\*SH $RSGTDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/log\/listSH.* $logDir \n";
    print FILE "mv \/scratch\/nfuji\/depth$depth\/log\/calLogSH.* $logDir \n";
    print FILE "exit\n";
    close FILE;
    

    open FILE, ">$execFile";
    print FILE "\#\!/bin/bash\n";
    print FILE "mpirun -np $npmpi $mpiSGTpsv < $inputFile > $logFile\n";
    print FILE "mpirun -np $npmpi $mpiSGTsh  < $inputFile > $logFileSH\n";
    close FILE;
    
    #system "chmod +x $execFile";
    
    system "chmod +x $qsubFile";
    system "qsub $qsubFile"; 
    
    system "chmod +x $qsubFile\.SH";
    system "qsub $qsubFile\.SH";

    

    #system "qsub $qsubFile";
    

}
